### ISSUE TITLE
Kmerstream sometimes fails when estimating the kmers to use

### ISSUE THREAD

**Issue by michaelbarton** [tseemann/shovill#10]
Here is the error message I recieve:

```
Running: seqtk sample R1.fq.gz 10000 | paste - - - - | cut -f2 > readsample.txt
Read length looks like 150 bp
Estimated K-mers: 21 37 53 69 85 101 117 [kn=8, ks=16, kmin=21, kmax=127]
Using kmers: 21,37,53,69,85,101,117
Estimating genome size
Running: KmerStream -k 21,37,53,69,85,101,117 -o kmerstream-raw.tsv -t 8 --tsv --verbose --online R1.fq.gz R2.fq.gz
Running: KmerStreamEstimate.py kmerstream-raw.tsv > kmerstream-est.tsv
Traceback (most recent call last):
  File "/usr/local/bin/KmerStreamEstimate.py", line 43, in <module>
    x,e = EMfit2(F0,f1,F1,int(k))
  File "/usr/local/bin/KmerStreamEstimate.py", line 26, in EMfit2
    e = brentq(func, 0, 1)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/zeros.py", line 415, in brentq
    r = _zeros._brentq(f,a,b,xtol,rtol,maxiter,args,full_output,disp)
ValueError: f(a) and f(b) must have different signs
Error 256 running command
```

I am using the version from commit `84e56564a`

**Comment by tseemann** [comment]
There are upstream bugs in Kmerstream:

* https://github.com/pmelsted/KmerStream/issues/11
* https://github.com/pmelsted/KmerStream/issues/12

I am waiting for @pmelsted to respond.

However I realise now his python code depends on `scipy` which is not something I want to depend on.

**Comment by michaelbarton** [comment]
Thanks for looking into this Torsten. A couple of options which don't use
scipy are kmergenie and bbtools. Perhaps @accopeland or @aclum can offer
some suggestions too.

**Comment by tseemann** [comment]
I've ditched KmerStream due to lack of response.

**Comment by michaelbarton** [comment]
Thanks @tseemann
